### ISSUE TITLE
Not Passing arguments in some function

### ISSUE THREAD

**Issue by HagegeR** [compas-dev/compas_cgal#12]
**Describe the bug**

While using the library (freshly installed from anaconda) I’ve found out that `meshing.py` function: `remesh` does not pass the argument `do_project` to the `meshing.remesh` call…

I’ll look out for other miss like that in the future and report here if it’s ok with you

**Comment by brgcode** [comment]
yes that would be great thanks!
could you try reinstalling? i added a new build yesterday evening to solve the problem with the missing requirements (`nptyping` and `typing_extensions`) and i think this problem should also be fixed in that build...

**Comment by HagegeR** [comment]
Hi, I’ve had a second interesting bug (but it’s linked to the viewer again): 

After selecting a mesh in the viewer and going to Geometry->Edit Object, an error occur saying that `edit()` (in `controller.py`) takes one argument but 2 were given. Maybe it’s the nested function? I don’t get why this gives an error :-\

unfortunately I had no time to check yet, but I’ll try this week to re-install the whole thing!

**Comment by brgcode** [comment]
no don't bother. those items in the menu don't work yet. i added them for testing and they somehow made it into the release unintentionally... :)

**Comment by brgcode** [comment]
i think this is solved...

**Comment by HagegeR** [comment]
Yes, thanks :)

Le sam. 22 janv. 2022 à 23:26, Tom Van Mele ***@***.***> a
écrit :
