### ISSUE TITLE
Implementation of CGAL functionality for surface reconstruction from point-clouds

### ISSUE THREAD

**Issue by dominikreisach** [compas-dev/compas_cgal#20]
# Feature Request

As a user of compas, I want an extension for surface reconstruction from point-clouds so that work with point-clouds without relying on 3rd party software.

## Details

**Is your feature request related to a problem? Please describe.**
As we discussed in the meeting on Monday (05.12.2022), a specific extension for point-cloud processing does not exist within the compas framework. We concluded that implementing the funcitonality provided by CGAL into _compas_cgal_ would be a first remedy.

**Describe the solution you'd like**
The three relevant algorithms are quite precisely described [here](https://doc.cgal.org/latest/Manual/tuto_reconstruction.html). It would be amazing to have them available.

**Describe alternatives you've considered**
Exploring Open3D's Python API in parallel (as discussed on Monday).

**Comment by tomvanmele** [comment]
not that the reconstruction function requires a clean input cloud. the point set processing part of the reconstruction pipeline still needs to be added...

**Comment by petrasvestartas** [comment]
If I understand correctly, mesh reconstruction often needs normal estimation and often raw scans do not have that.

This could be useful:

https://github.com/CGAL/cgal/blob/master/Point_set_processing_3/examples/Point_set_processing_3/normal_estimation.cpp

Also often it is necessary to have:
a) SOR - statictical outlier removal - to clean up the noisy points
b) And have a basic pointcloud decimation: a) random pointcloud removal or b) voxel based.

We can also build on top of that quite a lot of methods. I could also contribute.

**Comment by tomvanmele** [comment]
also added outlier_removal...
do we have some point clouds to test the functionality with?

**Comment by petrasvestartas** [comment]
Here are a few sets of scans:
https://mega.nz/file/J5YRlZRZ#_PBw30inPmxXWt2MTIjS7SqGpD9pPoaTobBPjlPlUY4

**Comment by petrasvestartas** [comment]
Added also polygonal_surface_reconstruction (https://doc.cgal.org/latest/Polygonal_surface_reconstruction/index.html):
This one requires an additional dependency:` libraries=["mpfr", "gmp", "libscip"]`, that is possible to install by `conda install scip`

<img width="853" alt="image" src="https://github.com/compas-dev/compas_cgal/assets/18013985/e1f4028f-cfc8-492a-8189-69905627e3dc">

**Comment by tomvanmele** [comment]
yes indeed :)
